#!/bin/sh

ng () {
	echo "${1} failed"
	res=1
}

#一定時間経過後にスクリプトを終了する関数を実装
test_script () {
	timeout 5s sh -c "
    echo ${1} | xvfb-run -a ./get_menues 
	"
}
res=0

#picturesに書き込み権限を付与
pwd
chmod -R 777 /
#予定通りの入力で正しく動作するか確認する
#新習志野1階メニュー
out=$( test_script s1 )
#タイムアウトによって終了すればよい
[ "$?" = 124 ] || ng "$LINENO" 
#新習志野2階メニュー
out=$( test_script s2 )
[ "$?" = 124 ] || ng "$LINENO" 
#津田沼1階メニュー
out=$( test_script t )
[ "$?" = 124 ] || ng "$LINENO" 


##想定外の入力でエラーを吐くか確認する
# 全く想定していない入力
out=$( test_script aa )
[ "$?" = 1 ] || ng "$LINENO" 
# スペルミス(1忘れ)
out=$( test_script s )
[ "$?" = 1 ] || ng "$LINENO" 
#入力された文字がないとき
out=$( test_script "" )
[ "$?" = 1 ] || ng "$LINENO"
#全角文字が入力されたとき
out=$( test_script 新習志野１階 )
[ "$?" = 1 ] || ng "$LINENO"  
#全角文字と半角文字が入力された場合
out=$(echo 新習志野1階 | xvfb-run -a ./get_menues)
[ "$?" = 1 ] || ng "$LINENO" 

[ "$res" = 0 ] && echo 'OK'

exit $res
