#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Horiguti 
# SPDX-License-Identifier: BSD-3-Clause
import sys


def tonum(num):
    try:
        return int(num)
    except ValueError:
        typ = type(num)
        raise KeyError(f"invalid value is inputed.that type is {typ}")


ans = 0
for l in sys.stdin:
    ans += tonum(l)

print(ans)
