#!/usr/bin/python3

import tkinter as tk
from PIL import Image, ImageTk

# ウィンドウを作成
root = tk.Tk()

# 画像を読み込む
image = Image.open("/home/RoboSys/robosys2024/pictures/menue.jpg")

#print(image)
# 画像のサイズを変更（幅300ピクセル、高さ300ピクセルにリサイズ）
resized_image = image.resize((500, 707), Image.ANTIALIAS)

# tkinterで表示できる形式に変換
tk_image = ImageTk.PhotoImage(resized_image)

# ラベルに画像を設定
label = tk.Label(root, image=tk_image)
label.pack()

# ウィンドウを表示
root.mainloop()
